package org.nekosukuriputo.nekuva.core.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0059C8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD9E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001944)
val md_theme_light_secondary = Color(0xFF575E71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDBE2F9)
val md_theme_light_onSecondaryContainer = Color(0xFF141B2C)
val md_theme_light_tertiary = Color(0xFF725573)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFDD7FB)
val md_theme_light_onTertiaryContainer = Color(0xFF2A132C)
val md_theme_light_error = Color(0xFFBA1B1B)
val md_theme_light_errorContainer = Color(0xFFFFDAD4)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F) // Same as onSurface
val md_theme_light_surface = Color(0xFFFBF8FD)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44464F)
val md_theme_light_outline = Color(0xFF757780)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFAFC6FF)
val md_theme_light_surfaceTint = Color(0xFF0059C8)

// Surface Containers
val md_theme_light_surfaceDim = Color(0xFFDBD9DD)
val md_theme_light_surfaceBright = Color(0xFFFBF8FD)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF5F3F7)
val md_theme_light_surfaceContainer = Color(0xFFEFEDF1)
val md_theme_light_surfaceContainerHigh = Color(0xFFE9E7EC)
val md_theme_light_surfaceContainerHighest = Color(0xFFE3E2E6)

val md_theme_dark_primary = Color(0xFFABC7FF)
val md_theme_dark_onPrimary = Color(0xFF002F65)
val md_theme_dark_primaryContainer = Color(0xFF00458F)
val md_theme_dark_onPrimaryContainer = Color(0xFFD7E3FF)
val md_theme_dark_secondary = Color(0xFFBEC6DC)
val md_theme_dark_onSecondary = Color(0xFF283041)
val md_theme_dark_secondaryContainer = Color(0xFF3E4759)
val md_theme_dark_onSecondaryContainer = Color(0xFFDAE2F9)
val md_theme_dark_tertiary = Color(0xFFDDBCE0)
val md_theme_dark_onTertiary = Color(0xFF3F2844)
val md_theme_dark_tertiaryContainer = Color(0xFF573E5C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFAD8FD)
val md_theme_dark_error = Color(0xFFFFB4AB) // Standard M3 Dark Error
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1B1F)
val md_theme_dark_onBackground = Color(0xFFC7C6CA) // Same as onSurface
val md_theme_dark_surface = Color(0xFF121316)
val md_theme_dark_onSurface = Color(0xFFC7C6CA)
val md_theme_dark_surfaceVariant = Color(0xFF44474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
val md_theme_dark_inversePrimary = Color(0xFF205DAF)
val md_theme_dark_surfaceTint = Color(0xFFABC7FF)

// Surface Containers
val md_theme_dark_surfaceDim = Color(0xFF121316)
val md_theme_dark_surfaceBright = Color(0xFF38393C)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0D0E11)
val md_theme_dark_surfaceContainerLow = Color(0xFF1A1B1F)
val md_theme_dark_surfaceContainer = Color(0xFF1F1F23)
val md_theme_dark_surfaceContainerHigh = Color(0xFF292A2D)
val md_theme_dark_surfaceContainerHighest = Color(0xFF343538)

// AMOLED Backgrounds
val amoled_surface = Color(0xFF080808)
val amoled_background = Color(0xFF000000)
val amoled_surfaceContainerLowest = Color(0xFF000000)
val amoled_surfaceContainerLow = Color(0xFF080808)
val amoled_surfaceContainer = Color(0xFF0C0C0C)
val amoled_surfaceContainerHigh = Color(0xFF101010)
val amoled_surfaceContainerHighest = Color(0xFF181818)
